import { DamagedPackagingItem } from '../types/warehouse';

export const initialDamagedPackagingData: DamagedPackagingItem[] = [
  {
    id: 'PKG-1',
    no: 1,
    packageNo: '1-SGSJ-A',
    serialNo: '496',
    plant: '1105',
    customer: 'PT. SETIA GUNA SEJATI',
    userScan: 'GUDANGRTP01',
    tglScanIn: '04/09/2026',
    jamScanIn: '19:26:42',
    kondisi: 'NG',
    slot: '',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: 'Dinding Pecah / Retak',
    labelItem: '',
    limbah: '',
    defectCategory: 'Dinding'
  },
  {
    id: 'PKG-2',
    no: 2,
    packageNo: '1-CPL0-A',
    serialNo: '2',
    plant: '1105',
    customer: 'PT. CIPTA PERDANA LANCAR',
    userScan: 'GUDANGRTP01',
    tglScanIn: '27/08/2026',
    jamScanIn: '01:14:38',
    kondisi: 'NG',
    slot: 'Bagian Pengunci Lepas',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Slot'
  },
  {
    id: 'PKG-3',
    no: 3,
    packageNo: '1-RPL0-C',
    serialNo: '56',
    plant: '1105',
    customer: 'PT. RODA PRIMA LANCAR',
    userScan: 'GUDANGRTP01',
    tglScanIn: '27/08/2026',
    jamScanIn: '01:14:38',
    kondisi: 'NG',
    slot: '',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: 'Dinding Pecah / Retak',
    labelItem: '',
    limbah: '',
    defectCategory: 'Dinding'
  },
  {
    id: 'PKG-4',
    no: 4,
    packageNo: '1-RPL0-C',
    serialNo: '1285',
    plant: '1105',
    customer: 'PT. RODA PRIMA LANCAR',
    userScan: 'GUDANGRTP01',
    tglScanIn: '27/08/2026',
    jamScanIn: '01:14:38',
    kondisi: 'NG',
    slot: 'Bagian Pengunci Lepas',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Slot'
  },
  {
    id: 'PKG-5',
    no: 5,
    packageNo: '1-DPM0-B',
    serialNo: '577',
    plant: '1105',
    customer: 'PT. METALINDO MULTIDINAMIKA MANDIRI',
    userScan: 'GUDANGRTP01',
    tglScanIn: '21/08/2026',
    jamScanIn: '13:54:51',
    kondisi: 'NG',
    slot: 'Bagian Pengunci Lepas',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Slot'
  },
  {
    id: 'PKG-6',
    no: 6,
    packageNo: '1-SGSL-A',
    serialNo: '63',
    plant: '1105',
    customer: 'PT. SETIA GUNA SELARAS',
    userScan: 'GUDANGRTP01',
    tglScanIn: '28/08/2026',
    jamScanIn: '01:33:32',
    kondisi: 'NG',
    slot: 'Bagian Pengunci Lepas',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Slot'
  },
  {
    id: 'PKG-7',
    no: 7,
    packageNo: '1-MMM0-A',
    serialNo: '45',
    plant: '1105',
    customer: 'PT. METALINDO MULTIDINAMIKA MANDIRI',
    userScan: 'GUDANGRTP01',
    tglScanIn: '01/09/2026',
    jamScanIn: '21:41:39',
    kondisi: 'NG',
    slot: 'Bagian Pengunci Lepas',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Slot'
  },
  {
    id: 'PKG-8',
    no: 8,
    packageNo: '1-GBL0-A',
    serialNo: '13',
    plant: '1105',
    customer: 'PT. METALINDO MULTIDINAMIKA MANDIRI',
    userScan: 'GUDANGRTP01',
    tglScanIn: '21/08/2026',
    jamScanIn: '13:54:51',
    kondisi: 'NG',
    slot: '',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: 'Dinding Pecah / Retak',
    labelItem: '',
    limbah: '',
    defectCategory: 'Dinding'
  },
  {
    id: 'PKG-9',
    no: 9,
    packageNo: '1-DPM0-I',
    serialNo: '195',
    plant: '1105',
    customer: 'PT. DHARMA POLIMETAL TBK.',
    userScan: 'GUDANGRTP01',
    tglScanIn: '27/08/2026',
    jamScanIn: '13:11:41',
    kondisi: 'NG',
    slot: '',
    kaki: '',
    rangka: '',
    pengait: '',
    dinding: 'Dinding Pecah / Retak',
    labelItem: '',
    limbah: '',
    defectCategory: 'Dinding'
  },
  {
    id: 'PKG-10',
    no: 10,
    packageNo: '1-IDM0-A',
    serialNo: '78',
    plant: '1105',
    customer: 'PT. SETIA GUNA SELARAS',
    userScan: 'GUDANGRTP01',
    tglScanIn: '14/08/2026',
    jamScanIn: '15:16:10',
    kondisi: 'NG',
    slot: '',
    kaki: '',
    rangka: 'Rangka Tidak Utuh',
    pengait: '',
    dinding: '',
    labelItem: '',
    limbah: '',
    defectCategory: 'Rangka'
  }
];
